on:
  delete
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI Build
        id: "deletebranch"
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.3
        env:
          CCI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.event.ref }} 