on:
  delete
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI Build
        id: "deletebranch"
        uses: circleci/trigger_circleci_pipeline@v1.0
        with:
          BRANCH_NAME: ${{ github.event.ref }} 
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}