on:
  delete
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI Build
        id: "deletebranch"
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: 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